# Generated by Django 5.1.2 on 2024-10-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bd',
            new_name='Bb',
        ),
    ]
